apiVersion: v1
kind: PersistentVolume  
metadata:
  name: studentapp-pv 
  labels:
    volume: test
spec:
  storageClassName: local
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: "/opt/studentapp/data"