apiVersion: apps/v1
kind: Deployment
metadata: 
  name: {{ .Values.metadata.deployment.app }}
  labels:
    app: {{ .Values.metadata.deployment.app }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels: 
      app: {{ .Values.metadata.deployment.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.metadata.deployment.app }}
    spec:
      containers:
        - name: {{ .Values.metadata.deployment.app }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.port.containerPort }}
          
          startupProbe:
            httpGet:
              path: {{ .Values.probes.path }}
              port: {{ .Values.probes.port }}
            initialDelaySeconds: {{ .Values.probes.initialDelaySeconds }}
            failureThreshold: {{ .Values.probes.failureThreshold }}
            periodSeconds: {{ .Values.probes.periodSeconds }}
          
          livenessProbe:  
            httpGet:
              path: {{ .Values.probes.path }}
              port: {{ .Values.probes.port }}
            periodSeconds: {{ .Values.probes.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.timeoutSeconds }}
          
          readinessProbe:  
            httpGet:
              path: {{ .Values.probes.path }}
              port: {{ .Values.probes.port }}
            periodSeconds: {{ .Values.probes.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.timeoutSeconds }}
          
          envFrom:
            - configMapRef:
                name: {{ .Values.configmap.name }}
            - secretRef:
                name: {{ .Values.secret.name }}
          
          resources: 
            requests:
              cpu: {{ .Values.resources.cpu }}
              memory: {{ .Values.resources.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
