apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-deployment
  labels:
    app: ecommerce-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecommerce
  template:
    metadata:
      labels:
        app: ecommerce
    spec:
      imagePullSecrets:
        - name: ecr-secret
        
      containers:
        - name: ecommerce
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8081

            #probes
          startupProbe:
            httpGet:
              path: /health
              port: 8081
            initialDelaySeconds: 30
            failureThreshold: 6
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8081
            periodSeconds: 10
            timeoutSeconds: 2
          readinessProbe:
            httpGet:
              path: /health
              port: 8081
            periodSeconds: 10
            timeoutSeconds: 2

          envFrom:
          - configMapRef:
              name: app-config
          - secretRef:
              name: ecommerce-db-secret         

            #resources quotas
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

        
---
apiVersion: v1
kind: Service
metadata:
 name: ecommerce-service
spec:
 type: ClusterIP
 selector:
   app: ecommerce
 ports:
   - name: http
     port: 8081   
     targetPort: 8081 
